# Generated by Django 5.0.6 on 2024-05-31 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_color_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_variant',
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='products.product'),
            preserve_default=False,
        ),
    ]
