# Generated by Django 5.0.6 on 2024-05-31 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_color_variant_colorvariant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.colorvariant'),
        ),
    ]
